Reactive
VolodymyrM27/AirGuardian pull request #9
Opened 2023-10-11 08:27 UTC by VolodymyrM27

@OleksandRomaniuk

2023-10-11 13:27 UTC, ajax-shulepa-a requested changes

2023-10-11 13:27 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/controller/DroneController.kt
> +
```suggestion
    fun getAllDrone(): Flux<DroneResponse> =
        droneService.getAllDrones().map { it.toResponse() }
```

2023-10-11 13:27 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/controller/DroneController.kt
> +    fun getAllDrone(): Flux<DroneResponse> =
how does it look for a client? One response with a list of DroneResponse or many responses?
If many responses, then consider changing the return type to Mono<List<DroneResponse>> as the goal of this endpoint is to return all elements and complete

2023-10-11 13:27 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/repository/DroneCustomReactiveRepository.kt
> +    fun findByStatus (droneStatus: DroneStatus): Flux<Drone>
```suggestion
    fun findAllByStatus (droneStatus: DroneStatus): Flux<Drone>
```
as method returns many items

2023-10-11 13:27 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/service/DeliveryOrderService.kt
> +            .filter { availableDrones -> availableDrones.isNotEmpty() }
```suggestion
            .filter { it.isNotEmpty() }
```
don't afraid to use 'it' when naming is not definitely needed. here it's easy to understand that you're checking that list is not empty

2023-10-11 13:27 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/service/DroneService.kt
> +            .then(Mono.empty())
if your method is completed normally, don't return empty mono, instead return Mono.just(Unit)

2023-10-11 13:32 UTC, VolodymyrM27 commented on src/main/kotlin/systems/ajax/motrechko/airguardian/controller/DroneController.kt
> +
In this suggestion no changes

2023-10-11 13:33 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/controller/DroneController.kt
> +
remove extra empty line

2023-10-12 16:07 UTC, VolodymyrM27 commented on src/main/kotlin/systems/ajax/motrechko/airguardian/service/DroneLogisticsService.kt
> +        drone.apply {
Is it mandatory, or is it a best practice for writing code?

2023-10-13 05:34 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/service/DroneLogisticsService.kt
> +        drone.apply {
for now, it is a best practice

2023-10-13 05:49 UTC, ajax-shulepa-a approved these changes
Fix minor issues, please

2023-10-13 05:49 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/service/DroneBatteryCheckService.kt
> +            )}
```suggestion
            .doOnSuccess{  
             logger.info(
                "A request has been received to charge a drone with an ID {}, which is now has {}%",
                drone.id, drone.batteryLevel
            )
            }
```

2023-10-13 05:49 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/service/DroneService.kt
> +            .flatMap { deletedResult ->
replace with handle operator

2023-10-13 05:49 UTC, ajax-shulepa-a commented on src/main/kotlin/systems/ajax/motrechko/airguardian/service/DroneService.kt
> +            .map { drones -> drones.map { it.toResponse() } }
```suggestion
        droneRepository.findAllByStatus(droneStatus)
            .map { it.toResponse() }
            .collectList()
```
let's have mapping reactive

2023-10-13 07:39 UTC, merged